Repository LegisLoop/LegisLoop, pull requests merged in 2025-02, with the labels that each got.

#10 Initial Legiscan Implementation
  legisloop-backend/src/main/java/com/backend/legisloop/controller/BillsController.java
  legisloop-backend/src/main/java/com/backend/legisloop/model/Bill.java
  legisloop-backend/src/main/java/com/backend/legisloop/model/Legislation.java
  legisloop-backend/src/main/java/com/backend/legisloop/model/LegislationDocument.java
  legisloop-backend/src/main/java/com/backend/legisloop/model/Representative.java
  legisloop-backend/src/main/java/com/backend/legisloop/service/BillService.java
  legisloop-backend/src/main/resources/application.properties
Labels: Enhancement

#9 bug: Fix lombok dependency in backend
  legisloop-backend/pom.xml
Labels: Bug

#15 Feature/Bill Service
  legisloop-backend/src/main/java/com/backend/legisloop/controller/BillsController.java
  legisloop-backend/src/main/java/com/backend/legisloop/model/Bill.java
  legisloop-backend/src/main/java/com/backend/legisloop/model/GoverningBody.java
  legisloop-backend/src/main/java/com/backend/legisloop/model/Legislation.java
  legisloop-backend/src/main/java/com/backend/legisloop/model/LegislationDocument.java
  legisloop-backend/src/main/java/com/backend/legisloop/service/BillService.java
Labels: Enhancement

#39 Refactor: Move LegiScan call verifier to Utils class
  legisloop-backend/src/main/java/com/backend/legisloop/Utils.java
  legisloop-backend/src/main/java/com/backend/legisloop/service/BillService.java
Labels: Refactor

#42 [FEATURE] Landing Page + Frontend Setup
  legisloop-frontend/package-lock.json
  legisloop-frontend/package.json
  legisloop-frontend/src/App.js
  legisloop-frontend/src/components/BillComponents/EventCard.js
  legisloop-frontend/src/components/BillComponents/LegislationPreviewCard.js
  legisloop-frontend/src/components/Footer/Footer.js
  legisloop-frontend/src/components/Icons/Icons.js
  legisloop-frontend/src/components/NavBar/NavBar.js
  legisloop-frontend/src/components/SearchBar/SearchBar.js
  legisloop-frontend/src/components/SideBar/SideBar.js
  legisloop-frontend/src/components/ToolTips/ToolTip.js
  legisloop-frontend/src/components/UnderConstruction/UnderConstruction.js
  legisloop-frontend/src/index.css
  legisloop-frontend/src/pages/ConnectPage.js
  legisloop-frontend/src/pages/LandingPage.js
  legisloop-frontend/src/pages/LegislationPage.js
  legisloop-frontend/src/pages/RepresentativePage.js
  legisloop-frontend/src/pages/SpendingPage.js
  legisloop-frontend/tailwind.config.js
Labels: Enhancement

#40 Add RollCall and associated handlers
  legisloop-backend/src/main/java/com/backend/legisloop/Utils.java
  legisloop-backend/src/main/java/com/backend/legisloop/controller/RollCallController.java
  legisloop-backend/src/main/java/com/backend/legisloop/enums/VotePosition.java
  legisloop-backend/src/main/java/com/backend/legisloop/model/Legislation.java
  legisloop-backend/src/main/java/com/backend/legisloop/model/RollCall.java
  legisloop-backend/src/main/java/com/backend/legisloop/model/Vote.java
  legisloop-backend/src/main/java/com/backend/legisloop/serial/BooleanSerializer.java
  legisloop-backend/src/main/java/com/backend/legisloop/service/BillService.java
  legisloop-backend/src/main/java/com/backend/legisloop/service/RollCallService.java
  legisloop-backend/src/test/java/com/backend/legisloop/UtilsTest.java
  legisloop-backend/src/test/java/com/backend/legisloop/controller/RollCallControllerTest.java
  legisloop-backend/src/test/java/com/backend/legisloop/service/RollCallServiceTest.java
Labels: Enhancement
