Repository LegisLoop/LegisLoop, pull requests merged in 2025-04, with the labels that each got.

#58 Fix the port of the generated Swaggers server
  docker-compose.yaml
  legisloop-backend/src/main/resources/application.properties
  nginx.conf
Labels: Blocker

#57 [FEATURE] Legislation Page
  legisloop-backend/src/main/java/com/backend/legisloop/controller/LegislationController.java
  legisloop-backend/src/main/java/com/backend/legisloop/controller/LegislationDocumentController.java
  legisloop-backend/src/main/java/com/backend/legisloop/entities/LegislationDocumentEntity.java
  legisloop-backend/src/main/java/com/backend/legisloop/entities/LegislationEntity.java
  legisloop-backend/src/main/java/com/backend/legisloop/model/Legislation.java
  legisloop-backend/src/main/java/com/backend/legisloop/model/LegislationDocument.java
  legisloop-backend/src/main/java/com/backend/legisloop/repository/LegislationDocumentRepository.java
  legisloop-backend/src/main/java/com/backend/legisloop/serial/DateSerializer.java
  legisloop-backend/src/main/java/com/backend/legisloop/service/InitializationService.java
  legisloop-backend/src/main/java/com/backend/legisloop/service/LegislationDocumentService.java
  legisloop-backend/src/main/java/com/backend/legisloop/service/LegislationService.java
  legisloop-backend/src/test/java/com/backend/legisloop/service/BillServiceTest.java
  legisloop-frontend/package-lock.json
  legisloop-frontend/package.json
  legisloop-frontend/public/TestHtml.html
  legisloop-frontend/src/App.js
  legisloop-frontend/src/components/Cards/EventCard.js
  legisloop-frontend/src/components/Cards/VoteCard.js
  legisloop-frontend/src/components/Footer/Footer.js
  legisloop-frontend/src/components/Icons/Icons.js
  legisloop-frontend/src/components/LegislationVisualizer/LegislationVisualizer.js
  legisloop-frontend/src/components/LegislationVisualizer/PdfJs.js
  legisloop-frontend/src/components/LegislationVisualizer/PdfViewer.js
  legisloop-frontend/src/components/LegislationVisualizer/sample.pdf
  legisloop-frontend/src/components/NavBar/NavBar.js
  legisloop-frontend/src/components/SideBar/LandingSideBar.js
  legisloop-frontend/src/components/SideBar/LegislationSideBar.js
  legisloop-frontend/src/index.js
  legisloop-frontend/src/pages/LandingPage.js
  legisloop-frontend/src/pages/LegislationPage.js
  legisloop-frontend/src/pages/SpendingPage.js
Labels: Enhancement

#67 Allow the SwaggerUI to init the backend by state
  legisloop-backend/src/main/java/com/backend/legisloop/controller/InitializationController.java
  legisloop-backend/src/main/java/com/backend/legisloop/service/InitializationService.java
Labels: Enhancement, Refactor

#68 Fixed a bug where federal bills were never fetched
  legisloop-frontend/src/customHooks/useLegislation.js
  legisloop-frontend/src/pages/LandingPage.js
Labels: Bug

#70 Feat/improve landing experience
  legisloop-frontend/src/components/Cards/LegislationPreviewCard.js
  legisloop-frontend/src/pages/LandingPage.js
Labels: Enhancement

#80 Fix bug regarding SQL date parsing
  legisloop-backend/src/main/java/com/backend/legisloop/service/LegislationService.java
  legisloop-backend/src/main/java/com/backend/legisloop/service/RepresentativeService.java
  legisloop-backend/src/main/java/com/backend/legisloop/task/UpdateDatabaseTasks.java
Labels: Bug

#81 Fixed a bug where switching between policies would not remove the old search results
  legisloop-frontend/src/customHooks/useLegislation.js
  legisloop-frontend/src/pages/LandingPage.js
Labels: Bug
