Repository LegisLoop/LegisLoop, pull requests merged in 2025-05, with the labels that each got.

#88 Fix/dont overwrite docs from zip
  legisloop-backend/src/main/java/com/backend/legisloop/model/Legislation.java
  legisloop-backend/src/main/java/com/backend/legisloop/service/InitializationService.java
  legisloop-backend/src/main/java/com/backend/legisloop/service/LegislationService.java
  legisloop-backend/src/main/java/com/backend/legisloop/task/UpdateDatabaseTasks.java
Labels: Bug

#89 Reset index of VoteEnum to 1-4
  legisloop-backend/src/main/java/com/backend/legisloop/enums/VotePosition.java
Labels: Blocker

#90 Fix favicon
  legisloop-frontend/public/favicon-192.png
  legisloop-frontend/public/favicon-512.png
  legisloop-frontend/public/logo192.png
  legisloop-frontend/public/logo512.png
  legisloop-frontend/public/manifest.json
  legisloop-frontend/src/logo.svg
Labels: Enhancement

#95 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: Documentation

#99 About Page
  legisloop-frontend/src/App.js
  legisloop-frontend/src/components/Footer/Footer.js
  legisloop-frontend/src/pages/AboutPage.js
Labels: Enhancement

#105 Fix tooltip bug to no longer cover essential features, and not show u…
  legisloop-frontend/src/components/SideBar/ConnectSideBar.js
  legisloop-frontend/src/components/SideBar/FindYourRepsSideBar.js
  legisloop-frontend/src/components/SideBar/LandingSideBar.js
  legisloop-frontend/src/components/SideBar/LegislationSideBar.js
  legisloop-frontend/src/components/Timeline/Timeline.js
  legisloop-frontend/src/components/ToolTips/ToolTip.js
  legisloop-frontend/src/pages/LandingPage.js
Labels: Bug

#108 Throw 404 for invalid LegislationDocument Lookup
  legisloop-backend/src/main/java/com/backend/legisloop/service/LegislationDocumentService.java
Labels: Bug

#106 Bug/timelinemobile
  legisloop-frontend/src/components/Timeline/Timeline.js
  legisloop-frontend/src/pages/RepresentativePage.js
Labels: Bug

#116 Added 2 events for expo prototype!
  legisloop-frontend/src/components/Cards/EventCard.js
  legisloop-frontend/src/pages/LandingPage.js
Labels: Enhancement

#111 [FEATURE] Legislation Page Info
  legisloop-backend/src/main/java/com/backend/legisloop/controller/RepresentativeController.java
  legisloop-frontend/src/components/Cards/LegislationPreviewCard.js
  legisloop-frontend/src/components/SideBar/LegislationSideBar.js
  legisloop-frontend/src/pages/LandingPage.js
  legisloop-frontend/src/pages/LegislationPage.js
Labels: Enhancement

#119 Landing Page State Preservation
  legisloop-frontend/src/App.js
  legisloop-frontend/src/context/landingPageContext.js
  legisloop-frontend/src/pages/LandingPage.js
Labels: Enhancement

#109 Remove Select Government Level from Find Your Representatives Page
  legisloop-frontend/src/components/SideBar/FindYourRepsSideBar.js
Labels: Enhancement

#124 Feat/recent bills beauty
  legisloop-frontend/src/App.js
  legisloop-frontend/src/components/Cards/LegislationPreviewCard.js
  legisloop-frontend/src/components/Cards/RepresentativesCard.js
  legisloop-frontend/src/pages/LandingPage.js
  legisloop-frontend/src/pages/LegislationPage.js
Labels: Enhancement

#129 [FEAT] Status Enum
  legisloop-backend/src/main/java/com/backend/legisloop/entities/LegislationEntity.java
  legisloop-backend/src/main/java/com/backend/legisloop/enums/StatusEnum.java
  legisloop-backend/src/main/java/com/backend/legisloop/enums/StatusEnumConverter.java
  legisloop-backend/src/main/java/com/backend/legisloop/model/Legislation.java
  legisloop-frontend/src/components/Cards/LegislationPreviewCard.js
  legisloop-frontend/src/pages/LandingPage.js
Labels: Enhancement

#130 [FEATURE] Styling for Generated Summaries
  legisloop-frontend/package-lock.json
  legisloop-frontend/package.json
  legisloop-frontend/src/components/Cards/SummaryCard.js
  legisloop-frontend/src/components/Cards/SummaryDisplayCard.js
  legisloop-frontend/src/pages/LegislationPage.js
Labels: Enhancement
